speed_jibe:
  -
    args:
      n: 3
    description: vmax_jibe
#deprecated_speed_jibe:
#  -
#    args:
#      n: 3
#    description: deprecated_vmax_jibe
planning_ratio:
  -
    args:
      v_min: 12
    description: planning_ratio>12
planning_distance:
  -
    args:
      v_min: 12
    description: planning_distance>12
v_moy:
  -
    args:
      v_min: 12
    description: Vmoy>12
speed_xs:
  -
    args:
      s: 1
      n: 2
    description: vmax_1s
  -
    args:
      s: 10
      n: 2
    description: vmax_10s
speed_dist:
  -
    args:
      dist: 500
      n: 1
    description: vmax_500m