rules:
  # gps analysis settings
  time_sampling: 1S # x seconds, recommend = 1S
  # sampling should match the sampling of the gpx trace
  # check trace informations in the execution.log
  # plus a warning will be issued if they differ
  max_acceleration: 0.22 # g
  # filter gps error spikes (chose a high value if you want to disable filtering)
  # acceleration = x g or 9.8x m/s/s or 20x knots/s, recommend values in [0.22 - 0.5] range
  # higher sampling (< 1S) require higher threshold (up to 0.8 with 0.1S sampling)
  max_speed: 45 # knots
  # filter backup: do not process file with remaining speeds > max_speed after filtering
  max_file_size: 10 # Mb : do not process file with size > max_file_size
  force_doppler_speed: false
  # for example doppler speed is automatically disabled for Movescount watch files
  # because the doppler field is not a true doppler value but just a 2/3 samples filter
  # use true if you want to (always) use the doppler speed field anyway
functions:
  # gps analysis functions to run and rank
  # do not repeat twice the same function (it is a dictionary structure)
  # instead repeat args list with different values and description
  speed_xs:
    -
      args:
        s: 1
        n: 1
      description: vmax_1s
      ranking_group: vmax
    -
      args:
        s: 10
        n: 1
      description: vmax_10s
      ranking_group: vmax
  speed_dist:
    -
      args:
        dist: 500
        n: 1
      description: vmax_500m
      ranking_group: vmax
    -
      args:
        dist: 1000
        n: 1
      description: vmax_1000m
      ranking_group: vmax
  planning_ratio:
    -
      args:
        v_min: 12
        distance: True
      description: planning_ratio>12
      ranking_group: rendement
  v_moy:
    -
      args:
        v_min: 12
      description: Vmoy>12
      ranking_group: rendement
  speed_jibe:
    -
      args:
        n: 5
      description: vmax_jibe
      ranking_group: jibe
  planning_distance:
    -
      args:
        v_min: 12
      description: planning_distance>12
      ranking_group: endurance
