
# sudo docker-compose -f docker-compose.yaml build --no-cache
# sudo docker-compose -f docker-compose.yaml up --force-recreate
# /var/lib/docker/volumes/docker_postgres_data
version: '3.2'
services:
#    nginx:
#        build:
#            context: ./
#            dockerfile: Dockerfile_nginx
#        container_name: nginx
#        depends_on:
#            - flask
#        networks:
#            - my-network
#        ports:
#            - 80:80
    keycloak:
        image: quay.io/keycloak/keycloak:12.0.4
        container_name: keycloak
        ports:
            - 8080:8080
        environment:
            - DB_VENDOR=POSTGRES
            - DB_ADDR=postgres
            - DB_PORT=5432
            - DB_DATABASE=flask
            - DB_USER=flask
            - DB_PASSWORD=flask
            - DB_SCHEMA=public
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        depends_on:
            - postgres

#    flask:
#        build:
#            context: ../
#            dockerfile: ./docker/Dockerfile_flask
#        container_name: flask
#        depends_on:
#            - postgres
#        volumes:
#            - ../:/gpsanapy
##            - ../gpx_file_upload:/gpsanapy/gpx_file_upload
##            - ../csv_results:/gpsanapy/csv_results
##            - ../config/:/gpsanapy/config
##        networks:
##            my-network:
##                aliases:
##                    - flask-app
#        ports:
#            - 9999:9999

    postgres:
        image: postgres:13-alpine
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            #- PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=flask
            - POSTGRES_PASSWORD=flask
            - POSTGRES_DB=flask

volumes:
  postgres_data:


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.13.0.0/24
#networks:
#    my-network:
#      ipam:
#        driver: bridge
#        config:
#          - subnet: 172.13.0.0/24

