# python flask container with gunicorn bind
# From docker directory:
# 	sudo docker build -t gpsana_restplus -f Dockerfile_flask_restx .
# 	sudo docker run -it --rm -p 80:8080 gpsana_restplus
# app running on address http://0.0.0.0 gpsana_restplus
#

FROM python:3.8
ARG BRANCH=restplus-api
ARG UID=1001
ARG GID=1001
ARG APP_USER=link_planner

ENV VIRTUAL_ENV=/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY ./requirements.txt ./requirements.txt
COPY ./flask_requirements.txt ./flask_requirements.txt

RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt
RUN pip install -r ./flask_requirements.txt
RUN git clone -b ${BRANCH} --single-branch https://github.com/jeanluc-auge/gpsanapy.git

RUN addgroup --gid $GID --system  ${APP_USER} &&\
    adduser --uid $UID --ingroup ${APP_USER} --system ${APP_USER}
# RUN mkdir /link_planner &&\
RUN chown -R ${UID}:${GID} /gpsanapy
USER ${APP_USER}

RUN mkdir /gpsanapy/csv_results
RUN mkdir /gpsanapy/gpx_file_upload
WORKDIR /gpsanapy/src/core
CMD gunicorn --bind 0.0.0.0:8080 -t 300 --workers=2 flask_restplus_server:app

