# config file: must be placed in config dir wrto project root dir
rules:
  # gps analysis settings
  time_sampling: 1S # x seconds, recommend = 1S
  # sampling should match the sampling of the gpx trace
  # check trace informations in the execution.log
  # plus a warning will be issued if they differ
  max_acceleration: 0.23 # 0.23g
  # filter gps error spikes (chose a high value if you want to disable filtering)
  # acceleration = x g or 9.8x m/s/s or 20x knots/s, recommend values in [0.22 - 0.5] range
  # higher sampling (< 1S) require higher threshold (up to 0.8 with 0.1S sampling)
  aggressive_filtering: false
  # do not activate for the majority of traces
  # but tighter filtering thresholds may help on very poor traces:
  # - increase filtering rolling window
  # - lower threshold for the activation of complex filtering (with return to normal conditions check)
  # this may result in the filtering of 'normal' speed periods
  max_speed: 45 # knots
  # filter backup: do not process file with remaining speeds > max_speed after filtering
  max_file_size: 16 # Mb : do not process file with size > max_file_size
  force_doppler_speed: false
  # for example doppler speed is automatically disabled for Movescount watch files
  # because the doppler field is not a true doppler value but just a 2/3 samples filter
  # use true if you want to (always) use the doppler speed field anyway
  parquet_loading: false
  # gpx files are interpreted and loaded into pandas DataFrame
  #     with filtering and resampling (raw gps data is also stored in the DataFrame)
  # but the gpx & html interpretation, sampling and filtering require a large computing time & power
  # The proposed feature saves the resulting pandas DataFrame in a fastparquet format
  #     (big data format with fast access & compression)
  #     subsequent re-analysis of the same file are performed with the DataFrame from the saved parquet file
  #     thereby saving large computing time (>80% saving)
  #     this doesn't affect gps analysis functions that are still re-calculated every time (not saved to parquet)
  #     and a sw versionning system automatically disables obsolete parquet files
  #     (for examples if there are changes in the sampling or filtering algorithm)
  #     however, the parquet loading can be disabled with this option (disable = false)
directory_paths:
  # files location path relative to the project root dir (requirements.txt & README.md dir)
  parquet_dir: parquet_files
  results_dir: csv_results
functions:
  # gps analysis functions to run and rank
  # do not repeat twice the same function (it is a dictionary structure)
  # instead repeat args list with different values and description
  speed_xs:
    -
      args:
        s: 1
        n: 5
      description: vmax_1s
      #ranking_group: vmax
    -
      args:
        s: 10
        n: 5
      description: vmax_10s
      ranking_group: vmax
    -
      args:
        s: 3600
        n: 1
      description: v_1h
      ranking_group: endurance
  speed_dist:
    -
      args:
        dist: 500
        n: 5
      description: vmax_500m
      #ranking_group: vmax
    -
      args:
        dist: 1000
        n: 5
      description: vmax_1000m
      #ranking_group: vmax
  planning_ratio:
    -
      args:
        v_min: 12
        distance: True
      description: planning_ratio>12
      #ranking_group: rendement
  v_moy:
    -
      args:
        v_min: 12
      description: Vmoy>12
      #ranking_group: rendement
  speed_jibe:
    -
      args:
        n: 5
      description: vmax_jibe
      ranking_group: technique
  planning_distance:
    -
      args:
        v_min: 12
      description: planning_distance>12
      #ranking_group: endurance
