name: Trigger auto deployment for gpsanapy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ windr-integration ]
    paths:
    - 'dockerfile/**'
    - '.github/workflows/gpsanapy-AutoDeployTrigger-9beeec94-bf1f-425c-8bcb-4c43a0499f02.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/windr-app/gpsanapy-debug:windr-integration
          username: ${{ secrets.GPSANAPY_REGISTRY_USERNAME }}
          password: ${{ secrets.GPSANAPY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/windr-app/gpsanapy-debug:windr-integration/gpsanapy:${{ github.sha }}
          file: ./dockerfile/Dockerfile
          context: ./dockerfile/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GPSANAPY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n gpsanapy -g windrgpsv1 --server ghcr.io/windr-app/gpsanapy-debug:windr-integration --username  ${{ secrets.GPSANAPY_REGISTRY_USERNAME }} --password ${{ secrets.GPSANAPY_REGISTRY_PASSWORD }}
            az containerapp update -n gpsanapy -g windrgpsv1 --image ghcr.io/windr-app/gpsanapy-debug:windr-integration/gpsanapy:${{ github.sha }}
